### ISSUE TITLE
Home Assistant Add-On crashes at boot

### ISSUE THREAD

**Issue by nickwilkie** [asmirnou/watsor#16]
I just installed the Home Assistant Add-On from the repository, and after configuring the bare minimum in /config/watsor/config.yaml I get this error:

jq: error: Could not open file /data/options.json: Permission denied
MainThread       root                     ERROR   : Either filename or data should be defined as input

Can't seem to change any configuration parameters to resolve this. For reference I'm running HASS on an x86 laptop inside a virtual machine and installed the standard (not RasPi) add-on. No problems currently with any other add-ons.

**Comment by asmirnou** [comment]
Apparently that happened after the permissions for all JSON files [were changed](https://github.com/home-assistant/supervisor/pull/2093) in the latest Supervisor.

Could you reload my add-on repository and try again? The user of the container [should now](https://github.com/asmirnou/watsor-hassio-addons/pull/3) have access to that file.

**Comment by nickwilkie** [comment]
Yep, that fixed it! Thanks
