### ISSUE TITLE
[FR] Seekable video archive

### ISSUE THREAD

**Issue by mfedderly** [asmirnou/watsor#20]
I've been looking at building something incredibly similar and stumbled across Watsor.

I'm interested in building a system that takes in live video, has real time person detection with messaging to HomeAssistant, and then also keeps that video around and has a web interface that lets a user seek around and look through older videos, for example when a person was detected.

Would you be interested in collaborating on this? I was planning to build the backend and frontend both in Typescript. I can try my hand at Python, but I can't promise that it will be good Python. My rough plan was to have ffmpeg take in the RSTP streams and output HLS that is then consumed by a backend that keeps track of all of the HLS chunks that get written out. I'm also happy to try to make something that sits along side Watsor and just requires a few ffmpeg flags to output the HLS in a way that I can consume.

**Comment by asmirnou** [comment]
I wrote it mostly for my own surveillance system (which is quite minimalistic) with no further plans to make NVR of it. Sorry, but I don't have much time to collaborate right now due to the focus on other things.

**Comment by mfedderly** [comment]
Totally understand, I am doing very much the same thing. I appreciate you paving the way for me on the AI stuff.
