### ISSUE TITLE
Accelerator in "Dev Board 3 with Edge TPU 4 TOPS"

### ISSUE THREAD

**Issue by vebmaster** [asmirnou/watsor#22]
Hello.

```Supports multiple hardware accelerators such as The Coral USB Accelerator and Nvidia CUDA GPUs to speed up detection algorithms.```

1) Is an accelerator used in "Dev Board 3 with Edge TPU 4 TOPS"? https://coral.ai/products/dev-board
2) Will an accelerator be used in "Dev Board 3 with Edge TPU" if there is a usb stick "The Coral USB Accelerator"?

**Comment by asmirnou** [comment]
Dev Board is a single-board computer that's already capable to perform fast machine learning inference. You don't need the Coral USB stick if Dev Board is used. What the quoted statement means is that there can multiple Coral USB sticks connected or several GPUs onboard and they all will equally split the load.

**Comment by vebmaster** [comment]
Спасибо Александр, не против если я по русски продолжу переписку. По руски еле еле мысль доношу.
Можете подсказать сколько потребуется TOPS, чтобы дектектировать объекты (людей/кошек/собак) и лица (заранее обучить на несколько человек).
7 видеопотоков 1920х1080, h.264 или mjpeg, до 5 фпс (может даже 2-3 фпс) на поток.
Т.е. сначала надо декодировать поток, затем найти объект. Т.е. двойная нагрузка получается.

Достаточно ли будет 4 TOPS от "Dev Board 3 with Edge TPU 4 TOPS"?
или понадобится jetson nano (2 TOPS), который сразу заявляет декодирование 8х1080p@30fps h.265 и к нему уже докупить usb стик coral (или более)

**Comment by asmirnou** [comment]
Сложно сказать, поэтому я бы начал с одного. Заявленные характеристики jetson nano завышены, это я обнаружил на собственном опыте. В производительности он уступает coral и тем более dev board. Производительность Coral может быть сильно ограничена пропускной способностью usb шины и электромагнитными наводками на кабель.
Смешивать устройства разных производителей точно не стоит, потому что запустить одну и ту же модель на jetson и на dev board не получится. У них разные форматы и оптимизация вычислений.
В разрешении 1920х1080 нет большого смысла, так как картинка все равно сжимается перед детектированием до размеров 300х300 или 640х640 в зависимости от модели, поэтому на передачу и декодирование большей картинки будет впустую уходить больше ресурсов. Лучше установить разрешение видеопотока близкое к размеру модели. Декодирование h.264 выполняется обычно другим чипом, чем детектирование, поэтому двойной нагрузки не будет.

**Comment by vebmaster** [comment]
> В разрешении 1920х1080 нет большого смысла

А если камера будет в 4к разрешении? Тоже нет смысла для детекции лиц на большом растоянии?
Или подбирается модель в высоком разрешении для 4к?

   
> Декодирование h.264 выполняется обычно другим чипом, чем детектирование

А на каком чипе декодируется видео у Coral Dev Board? На Cortex-M4F или на GPU GC7000 Lite?

> Производительность Coral может быть сильно ограничена пропускной способностью usb шины

Даже несмотря на USB 3?

**Comment by strarsis** [comment]
Is this TPU something that is shown in this LTT video?
https://www.youtube.com/watch?v=B635wcdr6-w
Could I also use a setup like that? VCR with GPU + TPU for max performance?

**Comment by asmirnou** [comment]
Yes, you can combine GPU and TPU devices in Watsor.
