### ISSUE TITLE
IPcam VCA/Dual VCA

### ISSUE THREAD

**Issue by strarsis** [asmirnou/watsor#23]
IPcam VCA feature allows to offload some types of recognition to the IPcam (outmost edge?).
With Dual VCA, the IPcam sends the interesting areas on a 2nd stream, so software can use it.
Do IPcams have a dedicated chipset for motion recognition that could help with performance in frigate?

Related issue for frigate: https://github.com/blakeblackshear/frigate/issues/2278

**Comment by asmirnou** [comment]
I don't know much about VCA, I suppose that if the 2nd stream is set up as camera input in Watsor it will be used for detection.

I don't think that any IP camera has a chipset capable to perform object detection inference.
