### ISSUE TITLE
Camera not able to reconnect after getting disconnected.

### ISSUE THREAD

**Issue by nandan06062g** [asmirnou/watsor#25]
if camera is getting disconnect for a few second also it is not able to reconnect. ffmpeg should have restart clause if frame is none.

**Comment by asmirnou** [comment]
The application monitors running processes and restarts them after 10 seconds if one was terminated by accident. Make sure that ffmpeg sub-process terminates when camera is disconnected. If it hangs forever, watsor won't be able to detect the failure.
