### ISSUE TITLE
Error on startup - google.protobuf.message.DecodeError: Truncated message.

### ISSUE THREAD

**Issue by srirams** [asmirnou/watsor#4]
Log file: https://pastebin.com/rrtQyCb2

I'm using the latest version of tensorflow (2.x) because I'm running python 3.8 and tensorflow 1 doesn't seem to be available for python >= 3.8.

**Comment by asmirnou** [comment]
It due to the wrong model file. The file `frozen_inference_graph.pb` inside the downloaded archive has to be renamed to `cpu.pb` and put into `model/` folder, `saved_model.pb` is for other purposes.

I'll make the documentation more clear about that.

**Comment by srirams** [comment]
Thanks, that fixed it! 

Seems to be working well, but it is missing a lot compared to frigate, but no false positives- whereas frigate has a better detection rate, but also a lot of false positives.

**Comment by asmirnou** [comment]
Good, closing as the problem is resolved.
